def ui_text(request):
    lang = request.session.get('lang', 'es')

    es = {
        'Dashboard': 'Dashboard',
        'Orders': 'Pedidos',
        'NewOrder': 'Nuevo pedido',
        'Pending': 'Pendientes',
        'Prepared': 'Preparados',
        'Delivered': 'Entregados',
        'Trips': 'Viajes',
        'NewTrip': 'Nuevo viaje',
        'Active': 'Activos',
        'Finished': 'Finalizados',
        'Products': 'Productos',
        'Entries': 'Entradas',
        'Stock': 'Stock',
        'ViewAll': 'Ver todos',
        'Clients': 'Clientes',
        'CurrentClients': 'Actuales',
        'PendingClients': 'Pendientes',
        'Administration': 'Administración',
        'Employees': 'Empleados',
        'Trucks': 'Camiones',
        'Suppliers': 'Proveedores',
        'Cuts': 'Cortes',
        'Cameras': 'Cámaras',
        'Reports': 'Reportes',
        'ReportStock': 'Stock',
        'ReportOrders': 'Pedidos',
        'ReportTrips': 'Viajes',
        'ReportExpiring': 'Productos por vencer',
        'Settings': 'Configuracion',
        'Language': 'Idioma',
        'Logout': 'Cerrar sesion',
        'Support': 'Soporte',
        'FilterBy': 'Filtrar por',
        'Search': 'Buscar...',
        'SearchByName': 'Buscar por nombre...',
        'Options': 'Opciones',
        'Apply': 'Aplicar',
        'Clear': 'Limpiar',
        'AllCommerces': 'Todos los comercios',
    }

    en = {
        'Dashboard': 'Dashboard',
        'Orders': 'Orders',
        'NewOrder': 'New order',
        'Pending': 'Pending',
        'Prepared': 'Prepared',
        'Delivered': 'Delivered',
        'Trips': 'Trips',
        'NewTrip': 'New trip',
        'Active': 'Active',
        'Finished': 'Finished',
        'Products': 'Products',
        'Entries': 'Entries',
        'Stock': 'Stock',
        'ViewAll': 'View all',
        'Clients': 'Clients',
        'CurrentClients': 'Current',
        'PendingClients': 'Pending',
        'Administration': 'Administration',
        'Employees': 'Employees',
        'Trucks': 'Trucks',
        'Suppliers': 'Suppliers',
        'Cuts': 'Cuts',
        'Cameras': 'Cameras',
        'Reports': 'Reports',
        'ReportStock': 'Stock',
        'ReportOrders': 'Orders',
        'ReportTrips': 'Trips',
        'ReportExpiring': 'Expiring products',
        'Settings': 'Settings',
        'Language': 'Language',
        'Logout': 'Log out',
        'Support': 'Support',
        'FilterBy': 'Filter by',
        'Search': 'Search...',
        'SearchByName': 'Search by name...',
        'Options': 'Options',
        'Apply': 'Apply',
        'Clear': 'Clear',
        'AllCommerces': 'All commerces',
    }

    return {
        'ui': en if lang == 'en' else es
    }
