# Generated by Django 5.2.8 on 2026-01-22 00:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cuit', models.IntegerField()),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cortes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado')], default='disponible', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('preparado', 'Preparado'), ('activo', 'Activo'), ('entregado', 'Entregado')], default='preparado', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Frigorifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('capacidad', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cuit', models.IntegerField()),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('encargado', 'Encargado')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rol_empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_frigorifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dias', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('dni', models.IntegerField()),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encargado.comercio')),
            ],
        ),
        migrations.CreateModel(
            name='Camiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('dominio', models.CharField(max_length=7)),
                ('disponibilidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='encargado.estado')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='encargado.carrito')),
                ('corte', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='encargado.cortes')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='activo', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='encargado.cliente')),
                ('comercio_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='encargado.comercio')),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='encargado.estadopedidos')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pedido_pendiente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encargado.pedido_cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedido',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('corte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encargado.cortes')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='encargado.pedido_cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilos', models.FloatField()),
                ('estado', models.CharField(choices=[('en stock', 'En stock'), ('preparado', 'preparado'), ('de viaje', 'De viaje'), ('entregado', 'Entregado')], default='en stock', max_length=15)),
                ('fecha_entrada', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='encargado.entrada')),
                ('frigorificop', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='encargado.frigorifico')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encargado.cortes')),
                ('temperatura', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='encargado.tipo_frigorifico')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('pedido_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='encargado.pedido')),
                ('producto_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='encargado.productos')),
            ],
            options={
                'verbose_name': 'Detalle Pedido',
                'verbose_name_plural': 'Detalles Pedidos',
                'db_table': 'detallepedido',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='entrada',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='encargado.proveedor'),
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('dni', models.IntegerField()),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.IntegerField()),
                ('disponibilidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='encargado.estado')),
                ('rol_empleado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='encargado.rol_empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('dni', models.IntegerField()),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.IntegerField()),
                ('rol', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='encargado.rol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('ayudante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='viajes_como_ayudante', to='encargado.empleados')),
                ('camion_viaje', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='encargado.camiones')),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='viajes_como_chofer', to='encargado.empleados')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='viaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='encargado.viaje'),
        ),
    ]
