# Generated by Django 5.2.8 on 2026-01-26 21:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encargado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='reserved_kilos',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado')], default='activo', max_length=10),
        ),
        migrations.CreateModel(
            name='IncidenteEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('atendido', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encargado.cliente')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encargado.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=30, unique=True)),
                ('fecha_entrada', models.DateTimeField()),
                ('fecha_vencimiento', models.DateTimeField()),
                ('kilos_disponibles', models.FloatField(default=0)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lote', to='encargado.productos')),
            ],
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilos_reserved', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('pedido_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='encargado.pedidoitem')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='encargado.productos')),
            ],
        ),
    ]
