# Generated by Django 4.2.24 on 2025-09-08 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encargado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos_guardados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precioxkg', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_frigorifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='productos',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='corte',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='precioxkg',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='total',
        ),
        migrations.AddField(
            model_name='productos',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=100),
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.DeleteModel(
            name='Corte',
        ),
        migrations.AlterField(
            model_name='frigorifico',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encargado.tipo_frigorifico'),
        ),
    ]
