# Generated by Django 5.2.6 on 2025-09-08 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encargado', '0002_productos_guardados_tipo_frigorifico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encargado.productos_guardados'),
        ),
    ]
