# Generated by Django 5.2.8 on 2025-12-19 05:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encargado', '0003_alter_productos_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pedido',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='encargado.usuarios'),
        ),
    ]
