# Generated by Django 5.2.8 on 2026-01-28 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encargado', '0003_historicaldetallepedido_historicalentrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='encargado.proveedor'),
        ),
        migrations.AlterField(
            model_name='historicalentrada',
            name='proveedor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='encargado.proveedor'),
        ),
        migrations.AlterField(
            model_name='historicalproductos',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
