# Generated by Django 5.2.8 on 2025-12-19 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encargado', '0004_pedido_creado_en_pedido_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['id'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='total',
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='pedido_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='encargado.pedido'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='producto_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='encargado.productos'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='pedido',
            table='pedido',
        ),
    ]
