# Generated by Django 5.2.8 on 2026-01-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encargado', '0004_alter_entrada_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='numero_lote',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='historicalentrada',
            name='numero_lote',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
    ]
