# Generated by Django 5.2.8 on 2025-12-19 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encargado', '0005_alter_pedido_options_remove_detallepedido_pedido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepedido',
            options={'ordering': ['id'], 'verbose_name': 'Detalle Pedido', 'verbose_name_plural': 'Detalles Pedidos'},
        ),
        migrations.AlterModelTable(
            name='detallepedido',
            table='detallepedido',
        ),
    ]
