# Generated by Django 5.2.8 on 2026-03-10 20:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encargado', '0005_entrada_numero_lote_historicalentrada_numero_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='estado_item',
            field=models.CharField(choices=[('ok', 'Ok'), ('perdido', 'Perdido'), ('danado', 'Dañado')], default='ok', max_length=10),
        ),
        migrations.AddField(
            model_name='historicaldetallepedido',
            name='estado_item',
            field=models.CharField(choices=[('ok', 'Ok'), ('perdido', 'Perdido'), ('danado', 'Dañado')], default='ok', max_length=10),
        ),
        migrations.CreateModel(
            name='IncidenteEntregaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_reportada', models.FloatField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('faltante', 'Faltante'), ('danado', 'Dañado'), ('equivocado', 'Equivocado'), ('otro', 'Otro')], default='faltante', max_length=20)),
                ('nota', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('atendido', models.BooleanField(default=False)),
                ('detalle_pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='encargado.detallepedido')),
                ('incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='encargado.incidenteentrega')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='encargado.productos')),
            ],
        ),
    ]
