# Generated by Django 5.2.8 on 2026-03-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encargado', '0006_detallepedido_estado_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductos',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productos',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
