# Generated by Django 5.2.8 on 2026-01-07 13:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encargado', '0007_proveedor_productos_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='fecha_vencimineto',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
