# Generated by Django 5.2.8 on 2026-01-08 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encargado', '0008_productos_fecha_vencimineto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrigorificoProducto',
        ),
    ]
