# Generated by Django 5.2.8 on 2026-01-08 16:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encargado', '0009_delete_frigorificoproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='productos',
            name='fecha_entrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='encargado.entrada'),
        ),
    ]
