# Generated by Django 5.2.8 on 2026-01-11 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encargado', '0010_entrada_alter_productos_fecha_entrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='entrada',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='encargado.proveedor'),
        ),
    ]
