# Generated by Django 5.2.8 on 2026-01-11 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encargado', '0011_remove_productos_proveedor_entrada_proveedor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos_guardados',
            new_name='Cortes',
        ),
    ]
