# Generated by Django 5.2.8 on 2026-01-11 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encargado', '0012_rename_productos_guardados_cortes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cortes',
            name='precioxkg',
        ),
        migrations.AddField(
            model_name='cortes',
            name='temperatura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='encargado.tipo_frigorifico'),
        ),
    ]
