# Generated by Django 5.2.8 on 2026-01-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encargado', '0013_remove_cortes_precioxkg_cortes_temperatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_frigorifico',
            name='dias',
            field=models.IntegerField(default=0),
        ),
    ]
