# Generated by Django 5.2.8 on 2026-01-11 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encargado', '0014_tipo_frigorifico_dias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cortes',
            name='temperatura',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='fecha_vencimineto',
        ),
        migrations.AddField(
            model_name='productos',
            name='temperatura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='encargado.tipo_frigorifico'),
        ),
    ]
