# Generated by Django 5.2.8 on 2026-01-11 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encargado', '0015_remove_cortes_temperatura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frigorifico',
            name='tipo',
        ),
    ]
