# Generated by Django 5.2.8 on 2026-01-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encargado', '0016_remove_frigorifico_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol_empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
