# Generated by Django 5.2.8 on 2026-01-12 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encargado', '0017_rol_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='rol_empleado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='encargado.rol_empleado'),
        ),
    ]
