# Generated by Django 5.2.8 on 2026-01-12 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encargado', '0018_empleados_rol_empleado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Camion',
            new_name='Camiones',
        ),
    ]
