# Generated by Django 5.2.8 on 2026-01-12 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encargado', '0019_rename_camion_camiones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camiones',
            name='disponibilidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='encargado.estado'),
        ),
    ]
