# Generated by Django 5.2.8 on 2026-01-14 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encargado', '0021_carrito_itemcarrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='producto',
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='corte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='encargado.cortes'),
        ),
    ]
