# Generated by Django 5.2.8 on 2026-01-14 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encargado', '0023_pedido_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('corte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encargado.cortes')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='encargado.pedido_cliente')),
            ],
        ),
    ]
