# Generated by Django 5.2.8 on 2026-01-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encargado', '0024_pedidoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_cliente',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='activo', max_length=20),
        ),
    ]
