# Generated by Django 5.2.8 on 2026-01-18 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encargado', '0025_alter_pedido_cliente_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='viaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='encargado.viaje'),
        ),
    ]
