# Generated by Django 5.2.8 on 2026-01-18 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encargado', '0026_alter_pedido_viaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='cantidad',
        ),
    ]
