# Generated by Django 5.2.8 on 2026-01-18 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encargado', '0027_remove_detallepedido_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comercio_origen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='encargado.comercio'),
        ),
    ]
