# Generated by Django 5.2.8 on 2026-01-18 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encargado', '0028_pedido_comercio_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='comercio_origen',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.RESTRICT, to='encargado.comercio'),
        ),
    ]
